project: spontaneous-movement

samplingRate: 20_000 # Hz

filter:
  drop_below: 20
  drop_above:

movement:
  tkeoMaxFreq: 10 # Hz
  tkeoThreshold: 0.013
  minEventLength: 0.1 # seconds
  minEventBreak: 0.1 # seconds
  expandBy: 0.1 # seconds

  minMovementAmplitude: 0.5 # (detection filter)
  minAmplitudeDifference: 0.25 # (quality filter)
  calmTime: 0.25 # seconds
