project: spontaneous-movement

sample_sheet: sample_sheet.csv

samplingRate: 20_000 # Hz

filter:
  emg:
    drop_below: 500
    drop_above: 2000
    scale: True
  vm:
    drop_below:
    drop_above:
    scale: False

movement:
  tkeoMaxFreq: 20 # Hz
  tkeoThreshold: 0.15
  maxTimeApart: 0.1 # Events closer will be merged
  maxLength: 2 # (s) Max event length
  minLength: 0.4 # (s) Min event length
  calmBeforeEvent: 0.5 # (s) required period with no events before movement onset
  minAmplitude: 1.5

no_movement:
  tkeoThreshold: 0.025
  minLength: 0.5 # seconds
  maxTimeApart: 0.1 # seconds
  expandBy: -0.1 # seconds (will shorten the event by cutting the edges off)

report:
  pages:
    - index
    - emg
    - vm
  supplementary:
    - figure1.png
#    TODO: fix figure 2, keeps breaking for some reason
#    - figure2.png
    - figure3.png
    - figure4.png
    - figure5.png
    - figure6.png
