project: spontaneous-movement

samplingRate: 20_000 # Hz

filter:
  emg:
    drop_below: 250
    drop_above: 2000
  vm:
    drop_below:
    drop_above:

movement:
  tkeoMaxFreq: 20 # Hz
  tkeoThreshold: 0.0025
  minEventLength: 0.1 # seconds
  minEventBreak: 0.1 # seconds
  expandBy: 0.2 # seconds

  minMovementAmplitude: 0.25 # (detection filter)
  minAmplitudeDifference: 0.1 # (quality filter)
  calmTime: 0.25 # seconds

  # Comparing events vs rest
  minAmplitudeDiff: 1.5
  smoothWindowSize: 200
  resampleFactor: 4

no_movement:
  tkeoThreshold: 0.0015
  minEventLength: 0.5 # seconds
  minEventBreak: 0.1 # seconds
  expandBy: -0.2 # seconds (will shorten the event by cutting the edges off)
